- .eslintrc
- .gitignore
- CHANGELOG.md
- package.json
- src/FindAuthority.js
- src/FindAuthority.test.js
- src/components/SearchModal/SearchModal.js
- src/components/SearchModal/SearchModal.test.js
- src/components/SearchModal/index.js
- src/components/index.js
- translations/ui-plugin-find-authority/en.json
Create an empty modal window
[UIPFAUTH-7](https://issues.folio.org/browse/UIPFAUTH-7)
> UIPFAUTH-7: Create an empty modal window for find Authorities plugin

- CHANGELOG.md
- package.json
`stripes-authority-components` must be included under `peerDependencies` instead of `dependencies` given that it is provided as a direct-dep by the platform
[UIPFAUTH-9](https://issues.folio.org/browse/UIPFAUTH-9)
> UIPFAUTH-9: move stripes-authority-components to peerDependencies

- CHANGELOG.md
- src/FindAuthority.js
- src/components/AuthoritiesLookup/AuthoritiesLookup.css
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
- src/components/AuthoritiesLookup/AuthoritiesLookup.test.js
- src/components/AuthoritiesLookup/index.js
- src/components/MarcAuthorityView/MarcAuthorityView.js
- src/components/MarcAuthorityView/MarcAuthorityView.test.js
- src/components/MarcAuthorityView/index.js
- src/components/index.js
- src/constants/base.js
- src/constants/index.js
- src/views/BrowseView/BrowseView.js
- src/views/BrowseView/BrowseView.test.js
- src/views/SearchView/SearchView.js
- src/views/SearchView/SearchView.test.js
- test/jest/__mock__/reactIntl.mock.js
View a MARC authority detail record.
Also, changes were fulfilled in:
- [ui-quick-marc](https://github.com/folio-org/ui-quick-marc/pull/353)
- [ui-marc-authorities](https://github.com/folio-org/ui-marc-authorities/pull/191)
- [stripes-authority-components](https://github.com/folio-org/stripes-authority-components/pull/14)
[UIPFAUTH-5](https://issues.folio.org/browse/UIPFAUTH-5)
https://user-images.githubusercontent.com/77053927/186112089-93a8f3d0-f0c3-4b5f-b6c7-ba657785f8b9.mp4
> UIPFAUTH-5: Select a MARC authority record modal > View a MARC authority detail record

- CHANGELOG.md
- src/components/AuthoritiesLookup/AuthoritiesLookup.css
Align heading/ref text to the left
[UIPFAUTH-15](https://issues.folio.org/browse/UIPFAUTH-15)
> UIPFAUTH-15 Browse: Long heading ref values in results list are not aligned to the left

- CHANGELOG.md
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
- src/views/BrowseView/BrowseView.js
- src/views/SearchView/SearchView.js
- src/views/SearchView/SearchView.test.js
- src/views/utils.js
- translations/ui-plugin-find-authority/en.json
- in the plugin retrieve only `Authorized` records for lookup types `Search` and `Browse`;
- in the plugin change the column name `Authorized/Reference` to `Authorized`;
- remove the `References` filter on the `Search`/`Browse` toggles.
Add a `references: ['excludeSeeFrom', 'excludeSeeFromAlso']` filter to request when the user selects/changes a filter or enters a search query to get only `Authorized` records.
[UIPFAUTH-11](https://issues.folio.org/browse/UIPFAUTH-11)
[UISAUTCOMP-12](https://issues.folio.org/browse/UISAUTCOMP-12) - cloned
https://user-images.githubusercontent.com/77053927/188610786-737ce0cc-134e-4075-b904-a73a9defd9fd.mp4
> UIPFAUTH-11: Default search query change to return - authRefType=Authorized

- CHANGELOG.md
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
Hide record counter in pane subtitle when Browsing records
[UIPFAUTH-19](https://issues.folio.org/browse/UIPFAUTH-19)
> UIPFAUTH-19 Hide counters when browsing records

- CHANGELOG.md
- src/components/AuthoritiesLookup/AuthoritiesLookup.css
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
- src/components/AuthoritiesLookup/AuthoritiesLookup.test.js
- src/views/SearchView/SearchView.js
- test/jest/__mock__/stripesComponents.mock.js
- add the `Expand the Search & filter pane` option to the results list;
- fix the [missing pagination buttons](https://user-images.githubusercontent.com/77053927/189202865-932f9932-db7c-4a3a-b090-bfdfacab6f72.mp4) ;
- keep the focus on the last selected list item after closing the detail view;
- fix offset by clicking on pagination (previously reset to 0).
[UIPFAUTH-16](https://issues.folio.org/browse/UIPFAUTH-16)
[UIMARCAUTH-182](https://issues.folio.org/browse/UIMARCAUTH-182)
[UISAUTCOMP-14](https://issues.folio.org/browse/UISAUTCOMP-14)
https://user-images.githubusercontent.com/77053927/189209460-f2f6dd4d-07c7-4c92-9862-0e3ec691baad.mp4
> UIPFAUTH-16: Add the Expand the Search & filter pane option

- CHANGELOG.md
- src/FindAuthority.js
- src/FindAuthority.test.js
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
- src/components/AuthoritiesLookup/AuthoritiesLookup.test.js
- src/components/MarcAuthorityView/MarcAuthorityView.js
- src/components/MarcAuthorityView/MarcAuthorityView.test.js
- src/components/SearchModal/SearchModal.js
- src/components/SearchModal/SearchModal.test.js
- src/views/BrowseView/BrowseView.js
- src/views/BrowseView/BrowseView.test.js
- src/views/SearchView/SearchView.js
- src/views/SearchView/SearchView.test.js
- translations/ui-plugin-find-authority/en.json
Handle linking of Authority record via details pane header
https://user-images.githubusercontent.com/19309423/189623469-b4b774f0-b3d0-418b-8a69-d17f073d956c.mp4
[UIPFAUTH-14](https://issues.folio.org/browse/UIPFAUTH-14)
https://github.com/folio-org/ui-quick-marc/pull/367
> UIPFAUTH-14 Detail Record : Click Link button to select a MARC authority record

- .eslintrc
- CHANGELOG.md
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
- src/constants/base.js
- translations/ui-plugin-find-authority/en.json
Show `Link` column in the plugin
https://user-images.githubusercontent.com/19309423/189883993-78b767a8-d31c-4813-8f36-61ac1b23d988.mp4
[UIPFAUTH-13](https://issues.folio.org/browse/UIPFAUTH-13)
https://github.com/folio-org/ui-marc-authorities/pull/199
https://github.com/folio-org/stripes-authority-components/pull/24
> UIPFAUTH-13 Results List : Click Link icon/button to select a MARC authority record

- CHANGELOG.md
- src/components/MarcAuthorityView/MarcAuthorityView.js
The `Search & filter` pane should not be the full width of the modal after the browser window is scaled.
[UIPFAUTH-26](https://issues.folio.org/browse/UIPFAUTH-26)
Also, this is a fix for [UIPFAUTH-27](https://issues.folio.org/browse/UIPFAUTH-27)
https://user-images.githubusercontent.com/77053927/191267103-250dece1-e8b4-4a03-899e-a2d3f4b2e299.mp4
> UIPFAUTH-26: The pane size of the "Search & filter" pane changes when user changes scale of the screen

- CHANGELOG.md
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
- src/views/BrowseView/BrowseView.test.js
Browse: Remove the link action on a placeholder row 
Link button is render if `authority` has an `id` property.
[UIPFAUTH-28](https://issues.folio.org/browse/UIPFAUTH-28)
> UIPFAUTH-28: remove the link action on a placeholder row

- CHANGELOG.md
- src/constants/base.js
Update columns widths so that the Heading type column values are not cut off.
[UIPFAUTH-31](https://issues.folio.org/browse/UIPFAUTH-31)
> UIPFAUTH-31: updated base column widths

- CHANGELOG.md
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
- src/components/MarcAuthorityView/MarcAuthorityView.js
- src/components/SearchModal/SearchModal.js
- src/constants/base.js
Have access to pagination buttons after scaling.
[UIPFAUTH-34](https://issues.folio.org/browse/UIPFAUTH-34)
https://user-images.githubusercontent.com/77053927/199540762-b0311f75-d4f8-4b9f-b917-00f3c3143431.mp4
> UIPFAUTH-34: The pagination buttons are missing when the user changes the scale of the screen

- CHANGELOG.md
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
Fix constant re-rendering after doing a search with one result.
[UIPFAUTH-37](https://issues.folio.org/browse/UIPFAUTH-37)
[UIMARCAUTH-204](https://github.com/folio-org/ui-marc-authorities/pull/217)
[UISAUTCOMP-30](https://github.com/folio-org/stripes-authority-components/pull/44)
https://user-images.githubusercontent.com/77053927/203528392-17239bf0-10f8-4454-840d-9edf943539d7.mp4
> UIPFAUTH-37: Error appears when the user executes search in "MARC Authority" app

- src/views/BrowseView/BrowseView.js
- src/views/SearchView/SearchView.js
- src/views/SearchView/SearchView.test.js
- src/views/utils.js
Fix not Authorized result showing after resetting filters
Need to always keep REFERENCES filter so only authorized records are searched
https://user-images.githubusercontent.com/19309423/209955436-e62b2d57-a614-4b6e-bf3b-cb0f41c6f44f.mp4
[UISAUTCOMP-34](https://issues.folio.org/browse/UISAUTCOMP-34)
> UIPFAUTH-36 fix not Authorized results in search

- CHANGELOG.md
- package.json
Bump stripes to 8.0.0
[UIPFAUTH-45](https://issues.folio.org/browse/UIPFAUTH-45)
[stripes-authority-components](https://github.com/folio-org/stripes-authority-components/pull/53)
> UIPFAUTH-45: bump stripes to 8.0.0 for Orchid/2023-R1

- CHANGELOG.md
- src/views/BrowseView/BrowseView.js
Browse: Fix Space at the begining and end of query string. The same fix as in UIMARCAUTH-251
[UIPFAUTH-59](https://issues.folio.org/browse/UIPFAUTH-59)
> UIPFAUTH-59

- CHANGELOG.md
- src/components/SearchModal/SearchModal.js
Fix for "Month" dropdown is Not displayed in date picker element opened in modal window
[UIPFAUTH-62](https://issues.folio.org/browse/UIPFAUTH-62)
> UIPFAUTH-62 "Month" dropdown is Not displayed in date picker element opened in modal window

- src/components/AuthoritiesLookup/AuthoritiesLookup.js
- src/views/BrowseView/BrowseView.js
- src/views/BrowseView/BrowseView.test.js
The focus should always be on the first result after clicking the previous/next button.
[UIPFAUTH-51](https://issues.folio.org/browse/UIPFAUTH-51)
[stripes-authority-components/pull/79](https://github.com/folio-org/stripes-authority-components/pull/79)
[ui-marc-authorities/pull/282](https://github.com/folio-org/ui-marc-authorities/pull/282)
https://user-images.githubusercontent.com/77053927/236485183-43286442-a9db-482a-8a8b-cbdea12002c1.mp4
> UIPFAUTH-51: Fix the focus of the first result for the Browse search

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
Update Node.js to v18 in GitHub Actions
[UIPFAUTH-70](https://issues.folio.org/browse/UIPFAUTH-70)
> UIPFAUTH-70 Update Node.js to v18 in GitHub Actions

- CHANGELOG.md
- src/components/MarcAuthorityView/MarcAuthorityView.js
- src/components/utils.js
Add `Local` or `Shared` to flag MARC authorities.
https://github.com/folio-org/ui-quick-marc/pull/578
https://github.com/folio-org/ui-marc-authorities/pull/304
https://github.com/folio-org/stripes-authority-components/pull/94
[UIPFAUTH-73](https://issues.folio.org/browse/UIPFAUTH-73)
> UIPFAUTH-73: Add 'Local' or 'Shared' to flag MARC authorities.

- CHANGELOG.md
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
- src/components/AuthoritiesLookup/AuthoritiesLookup.test.js
Add Shared icon to Find authority plugin search results
[UIPFAUTH-74](https://issues.folio.org/browse/UIPFAUTH-74)
https://github.com/folio-org/stripes-authority-components/pull/97
https://github.com/folio-org/ui-marc-authorities/pull/305
> UIPFAUTH-74 Add Shared icon to Find authority plugin search results

- CHANGELOG.md
- src/components/MarcAuthorityView/MarcAuthorityView.js
- src/components/MarcAuthorityView/MarcAuthorityView.test.js
- test/jest/__mock__/stripesCore.mock.js
Change tenant id to central when opening details of Shared Authority
[UIPFAUTH-75](https://issues.folio.org/browse/UIPFAUTH-75)
https://github.com/folio-org/ui-marc-authorities/pull/306
https://github.com/folio-org/stripes-authority-components/pull/99
https://github.com/folio-org/ui-quick-marc/pull/580
> UIPFAUTH-75  Change tenant id to central when opening details of Shared Authority

- CHANGELOG.md
- src/FindAuthority.js
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
- src/components/SearchModal/SearchModal.js
- src/views/BrowseView/BrowseView.js
- src/views/BrowseView/BrowseView.test.js
- src/views/SearchView/SearchView.js
- src/views/SearchView/SearchView.test.js
Link Shared/Local MARC bib record to Shared/Local Authority record.
[UIPFAUTH-76](https://issues.folio.org/browse/UIPFAUTH-76)
https://github.com/folio-org/ui-quick-marc/pull/581
https://github.com/folio-org/stripes-authority-components/pull/100
https://github.com/folio-org/ui-inventory/pull/2242
https://github.com/folio-org/ui-plugin-find-authority/assets/77053927/dbda37b0-a265-4475-b4cc-b984c65988cc
> UIPFAUTH-76: Link Shared/Local MARC bib record to Shared/Local Authority record.

- CHANGELOG.md
- src/FindAuthority.js
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
- src/components/SearchModal/SearchModal.js
- src/views/BrowseView/BrowseView.js
- src/views/BrowseView/BrowseView.test.js
- src/views/SearchView/SearchView.js
- src/views/SearchView/SearchView.test.js
Hide the Shared facet in the plugin for the shared bib record.
https://github.com/folio-org/ui-quick-marc/pull/585
https://github.com/folio-org/stripes-authority-components/pull/103
[UISAUTCOMP-72](https://issues.folio.org/browse/UISAUTCOMP-72)
https://github.com/folio-org/ui-plugin-find-authority/assets/77053927/7f01da8e-e521-4414-b3d9-d9a0a23c2b4f
> UIPFAUTH-77: Hide the Shared facet in the plugin for the shared bib record.

- CHANGELOG.md
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
- src/views/BrowseView/BrowseView.js
- src/views/BrowseView/BrowseView.test.js
Don't clear previous Search/Browse results to highlight the edited record.
Keeping previous results fixes the current issue, but occasionally leads to incorrect row focus in the `Browse` search after clicking the pagination buttons (when the previous page has fewer results than the next one) ([UIPFAUTH-51](https://issues.folio.org/browse/UIPFAUTH-51)) 
The newly added `pagingOffset` prop in the `stripes-components` allows always focus on the first row after pagination buttons are clicked.
[UIPFAUTH-80](https://issues.folio.org/browse/UIPFAUTH-80)
https://github.com/folio-org/stripes-authority-components/pull/110
https://github.com/folio-org/ui-marc-authorities/pull/315
https://github.com/folio-org/ui-plugin-find-authority/assets/77053927/7a7cc127-434c-48b3-ba69-67d06402e27d
> UIPFAUTH-80: Don't clear previous Search/Browse results to highlight the edited record.

- CHANGELOG.md
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
- src/views/BrowseView/BrowseView.js
- src/views/BrowseView/BrowseView.test.js
Remove unnecessary `pagingOffset` prop.
[UIPFAUTH-81](https://issues.folio.org/browse/UIPFAUTH-81)
https://github.com/folio-org/stripes-components/pull/2126
https://github.com/folio-org/stripes-authority-components/pull/111
https://github.com/folio-org/ui-marc-authorities/pull/317
> UIPFAUTH-81: Remove unnecessary pagingOffset prop.

- CHANGELOG.md
- package.json
- src/components/MarcAuthorityView/MarcAuthorityView.js
- src/temp/QuickMarcView/MarcContent/MarcContent.css
- src/temp/QuickMarcView/MarcContent/MarcContent.js
- src/temp/QuickMarcView/MarcContent/MarcContent.test.js
- src/temp/QuickMarcView/MarcContent/index.js
- src/temp/QuickMarcView/MarcField.css
- src/temp/QuickMarcView/MarcField.js
- src/temp/QuickMarcView/QuickMarcView.js
- src/temp/QuickMarcView/QuickMarcView.test.js
- src/temp/QuickMarcView/utils.js
There is a circular dependency between between `ui-plugin-find-authority` and `ui-quick-marc`.
`ui-quick-marc` uses `ui-plugin-find-authority` as a plug-in for Linking Authority records, so we can't remove this dependency
That leaves with removing `ui-plugin-find-authority` dependency on `ui-quick-marc`. We need to copy imported code from `ui-quick-marc` and update `package.json`.
[UIPFAUTH-83](https://issues.folio.org/browse/UIPFAUTH-83)
> UIPFAUTH-83 Resolve circular dependency with ui-quick-marc. Clone QuickMarcView component from `ui-quick-marc`.

- CHANGELOG.md
- package.json
Remove eslint deps that are already listed in eslint-config-stripes.
[UIPFAUTH-72](https://issues.folio.org/browse/UIPFAUTH-72)
> UIPFAUTH-72: Remove eslint deps that are already listed in eslint-config-stripes.

- CHANGELOG.md
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
- src/components/AuthoritiesLookup/AuthoritiesLookup.test.js
- src/constants/base.js
- translations/ui-plugin-find-authority/en.json
Add a new column called `Authority source` for the browse and search results.
[UIPFAUTH-86](https://issues.folio.org/browse/UIPFAUTH-86)
https://github.com/folio-org/stripes-authority-components/pull/126
https://github.com/folio-org/ui-marc-authorities/pull/328
https://github.com/folio-org/ui-plugin-find-authority/assets/77053927/bff2f1fc-c3db-4f80-b907-2ca0effa6978
> UIPFAUTH-86: Add new column called Authority source for the browse and search results.

- CHANGELOG.md
- src/views/BrowseView/BrowseView.js
- src/views/BrowseView/BrowseView.test.js
Fix Facet counts changing when going Next or Prev page in Browse
Use first page query to fetch Browse facets
https://github.com/folio-org/ui-plugin-find-authority/assets/19309423/8696576a-ae72-4e00-8c9f-68512a33193a
[UIPFAUTH-87](https://issues.folio.org/browse/UIPFAUTH-87)
https://github.com/folio-org/ui-marc-authorities/pull/333
https://github.com/folio-org/stripes-authority-components/pull/130
> UIPFAUTH-87 Use first page Browse query for facet requests

- CHANGELOG.md
- src/components/AuthoritiesLookup/AuthoritiesLookup.js
Fix issue with facet counts not changing when using different browse options.
It was caused by missing query parameters in `useFacets` request so all facets requests were sent with `id=*`.
We need to pass `firstPageQuery` prop to `<AuthoritiesSearchPane>` to pass the query to facets requests.
https://github.com/user-attachments/assets/731c6303-3652-4193-b0c2-39daea12a005
[UIPFAUTH-104](https://folio-org.atlassian.net/browse/UIPFAUTH-104)
> UIPFAUTH-104 Pass `firstPageQuery` to `<AuthoritiesSearchPane>` to include query in facets request.

- CHANGELOG.md
- package.json
migrate stripes deps and react-intl to sunflower versions
[UIPFAUTH-106](https://folio-org.atlassian.net/browse/UIPFAUTH-106)
[UIPFAUTH-107](https://folio-org.atlassian.net/browse/UIPFAUTH-107)
> migrate stripes deps and react-intl to sunflower versions
